[package]
name = "bevy_gearbox"
version = "0.1.2"
edition = "2021"
description = "State machine system for the bevy game engine"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.15"
bevy_ecs = { version = "0.15.0", default-features = false }
bevy_gearbox_macros = "0.1.0"

[dev-dependencies]
bevy = { version = "0.15", features = ["default"] }
