[package]
name = "bevy_gearbox"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_ecs = { version = "0.15.0", default-features = false }
bevy_gearbox_macros = { path = "./macros" }

[dev-dependencies]
bevy = { version = "0.15", features = ["default"] }
